version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Main-Application
    environment:
      DB_URL: jdbc:postgresql://sch-university-db:5432/schedule_university
      DB_USER: abuser
      DB_PASSWORD: abuser
    ports:
      - "8080:8080"
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: sch-university-db
    environment:
      POSTGRES_USER: abuser
      POSTGRES_PASSWORD: abuser
      POSTGRES_DB: schedule_university
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  postgres_data: